export const enum ClientStatusType {
  ACTIVO = 'ACTIVO',
  SOLICITUD = 'SOLICITUD',
  APROBADO = 'APROBADO',
  VERIFICADO = 'VERIFICADO',
  DECLINADO = 'DECLINADO',
  CANCELADO = 'CANCELADO',
  PAUSADO = 'PAUSADO'
}
