export const enum CompanyType {
  NAVIERA = 'NAVIERA',
  TRANSPORTISTA = 'TRANSPORTISTA',
  PERSONA_MORAL = 'PERSONA_MORAL',
  PERSONA_FISICA = 'PERSONA_FISICA',
  CONTRATISTA = 'CONTRATISTA',
  AGENTE_ADUANAL = 'AGENTE_ADUANAL',
  GOBIERNO = 'GOBIERNO',
  CENTRO_DE_DISTRIBUCION = 'CENTRO_DE_DISTRIBUCION'
}
