export const enum ContactType {
  TELEFONO = 'TELEFONO',
  EMAIL = 'EMAIL',
  WEBSITE = 'WEBSITE',
  FACEBOOK = 'FACEBOOK',
  TWITTER = 'TWITTER',
  INSTAGRAM = 'INSTAGRAM',
  LINKEDIN = 'LINKEDIN',
  WHATSAPP = 'WHATSAPP'
}
