export const enum ContractType {
  PRESTACION_DE_SERVICIO = 'PRESTACION_DE_SERVICIO',
  TERMINOS_Y_CONDICIONES = 'TERMINOS_Y_CONDICIONES',
  DECISION_INTERNA = 'DECISION_INTERNA',
  SOLICITUD_DE_SERVICIO = 'SOLICITUD_DE_SERVICIO',
  SOLICITU_DE_MANIOBRA = 'SOLICITU_DE_MANIOBRA',
  INSPECCION = 'INSPECCION',
  EMPLEADO = 'EMPLEADO',
  CONFIDENCIALIDAD = 'CONFIDENCIALIDAD'
}
