export const enum DivisionType {
  INTERMODAL = 'INTERMODAL',
  FERTILIZANTES = 'FERTILIZANTES',
  POLIETILENO = 'POLIETILENO',
  TUBERIA = 'TUBERIA',
  LACTEOS = 'LACTEOS',
  CERVEZA = 'CERVEZA',
  SAGARPA = 'SAGARPA'
}
