export const enum ServiceType {
  CARGA = 'CARGA',
  DESCARGA = 'DESCARGA',
  TRANSPORTE = 'TRANSPORTE',
  IMPORTACION = 'IMPORTACION',
  EXPORTACION = 'EXPORTACION',
  ALMACENAJE = 'ALMACENAJE',
  INSPECCION = 'INSPECCION',
  REPARACION = 'REPARACION',
  CROSS_DOCK = 'CROSS_DOCK'
}
